### ISSUE TITLE
assets:precompile task runs in separate container

### ISSUE THREAD

**Issue by JamesCarscadden** [netguru/capistrano-docker#3]
Including the 'capistrano/docker/assets' task into the Capfile seems like a nice clean way to accomplish this task, but currently this runs in a separate instance of the container - which to my understanding of containers means that the final container that is run won't actually have the assets pre-compiled as it is a separate instance. I presume then that you are using volumes in some way (data only container?) rather than 'ADD'ing all your rails project files into the container. Is there an example somewhere of how this task should be used?

**Comment by rindek** [comment]
@JamesCarscadden you are correct, including `capistrano/docker/assets` to work properly requires you to use a volume, or volume-only container.

The way rails is deployed can be trouble-ish (due to additional tasks, like assets and/or db migration). I have tried couple solutions, such as:
- commit precompile assets to repository
- precompile assets directly in Dockerfile
- precompile assets when containers starts (in entrypoint)

Although none of above "fits" my needs as I wanted - so I came with this solution. Of course - you don't have to use it to precompile assets, you can use one of the solutions I listed above. It's just running precompilation task is seperate container with volume attached seems to be "the cleanest" way :)

An example with using this can be found in one of our open-source apps. The task is added in Capfile here: https://github.com/netguru/people/blob/master/Capfile#L8, and the volume is attached here: https://github.com/netguru/people/blob/master/config/deploy/staging.rb#L10

**Comment by rindek** [comment]
I'll close this issue for now. If you have any more questions please re-open
